# KTPlace Top-level Makefile
# This is the entry point for building the entire project

.PHONY: all clean rebuild test check help format format-check clang-format hooks compile-commands

# Default target - build from src directory
all:
	@$(MAKE) -C src -f Master.make all

# Clean
clean:
	@$(MAKE) -C src -f Master.make clean

# Rebuild
rebuild:
	@$(MAKE) -C src -f Master.make rebuild

# Build and run the unit tests: the engine suites plus the web console's own
# (stdlib unittest, no build needed -- it serves fixtures, not the tree).
test:
	@$(MAKE) -C src -f Master.make test
	@echo "--- webui ---"
	@python3 webui/test/test_server.py

check: test

# Rewrite every source file in place with clang-format.
format:
	@git ls-files 'src/*.cc' 'src/*.h' | grep -v '^src/visualization/CImg.h$$' > /tmp/ktplace-fmt.$$
	@n=$$(wc -l < /tmp/ktplace-fmt.$$); \
	 xargs --no-run-if-empty clang-format -i < /tmp/ktplace-fmt.$$; \
	 rm -f /tmp/ktplace-fmt.$$; \
	 echo "formatted $$n file(s)"


# Report what format would change, without touching anything. Exits non-zero if
# anything is unformatted, so it can gate a commit or a CI job.
format-check:
	@git ls-files 'src/*.cc' 'src/*.h' | grep -v '^src/visualization/CImg.h$$' | \
		xargs --no-run-if-empty clang-format --dry-run --Werror

# Compilation database for clangd, so it can find the project's headers and jump
# to a definition. Regenerated by `make compile-commands`; the file is not
# tracked, because it is machine-specific in spirit even though it is written
# with relative paths, and a stale one is worse than none.
compile-commands:
	@python3 scripts/gen_compile_commands.py

# Which clang-format would be used, and what version it is. Worth knowing before
# running format on a tree, since a different major version lays the file out
# differently and produces a diff that is style, not substance.
clang-format:
	@command -v clang-format || { echo "clang-format not found on PATH"; exit 1; }
	@clang-format --version

# Help
# Install the repository's git hooks by pointing core.hooksPath at them, so the
# hook is shared through the tree rather than copied into .git/hooks by hand.
hooks:
	@git config core.hooksPath .githooks
	@echo "core.hooksPath = $$(git config core.hooksPath)"
	@echo "pre-commit now checks staged formatting and runs the unit tests."
	@echo "Bypass with KTPLACE_SKIP_HOOKS=1; skip just the tests with KTPLACE_HOOK_TESTS=0."

help:
	@echo "KTPlace Top-level Build System"
	@echo "=============================="
	@echo "Targets:"
	@echo "  all           - Build the project (default)"
	@echo "  clean         - Remove build artifacts"
	@echo "  rebuild       - Clean and rebuild"
	@echo "  test          - Build and run the unit tests (alias: check)"
	@echo "  format        - Rewrite the sources with clang-format"
	@echo "  format-check  - Report formatting problems, changing nothing"
	@echo "  clang-format  - Show which clang-format would be used"
	@echo "  hooks           - Install the git hooks (pre-commit checks format + tests)"
	@echo "  compile-commands - Write compile_commands.json for clangd"
	@echo "  help          - Show this help message"
	@echo ""
	@echo "Run 'make help' in src/ for more detailed options."

